sylius_ui:
    events:
        sylius.shop.layout.javascripts:
            blocks:
                omnisend:
                    template: "@NFQSyliusOmnisendPlugin/Shop/Layout/_javascript.html.twig"
                    priority: 0

        sylius.shop.product.show.after_description:
            blocks:
                omnisend:
                    template: "@NFQSyliusOmnisendPlugin/Shop/Product/_product_picker.html.twig"
                    priority: 0
