nfq_sylius_omnisend_event:
  resource: |
    alias: nfq_sylius_omnisend_plugin.event
    section: admin
    except: ['show']
    templates: SyliusAdminBundle:Crud
    redirect: update
    grid: nfq_sylius_omnisend_event
    form: NFQ\SyliusOmnisendPlugin\Form\Type\EventType
  type: sylius.resource
  prefix: admin
