services:
  nfq_sylius_omnisend_plugin.form.extension.type.channel:
    class: NFQ\SyliusOmnisendPlugin\Form\Extension\ChannelFormTypeExtension
    tags:
      - { name: form.type_extension, extended_type: Sylius\Bundle\ChannelBundle\Form\Type\ChannelType }

  nfq_sylius_omnisend_plugin.block_event_listener.sylius.admin.channel.update:
    class: Sylius\Bundle\UiBundle\Block\BlockEventListener
    arguments:
      - '@@NFQSyliusOmnisendPlugin/Channel/Admin/_channel_omnisend_key.html.twig'
    tags:
      - { name: kernel.event_listener, event: sonata.block.event.sylius.admin.channel.update.form, method: onBlockEvent }

  nfq_sylius_omnisend_plugin.block_event_listener.sylius.admin.channel.create:
    class: Sylius\Bundle\UiBundle\Block\BlockEventListener
    arguments:
      - '@@NFQSyliusOmnisendPlugin/Channel/Admin/_channel_omnisend_key.html.twig'
    tags:
      - { name: kernel.event_listener, event: sonata.block.event.sylius.admin.channel.create.form, method: onBlockEvent }

  nfq_sylius_omnisend_plugin.block_event_listener.sylius.shop.layout.javascripts:
    class: Sylius\Bundle\UiBundle\Block\BlockEventListener
    arguments:
      - '@@NFQSyliusOmnisendPlugin/Shop/Layout/_javascript.html.twig'
    tags:
      - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.layout.javascripts, method: onBlockEvent }

  nfq_sylius_omnisend_plugin.block_event_listener.sylius.product.show.content:
    class: Sylius\Bundle\UiBundle\Block\BlockEventListener
    arguments:
      - '@@NFQSyliusOmnisendPlugin/Shop/Product/_product_picker.html.twig'
    tags:
      - { name: kernel.event_listener, event: sonata.block.event.sylius.shop.product.show.after_description, method: onBlockEvent }

  nfq_sylius_omnisend_plugin.resolver.product_image:
    class: NFQ\SyliusOmnisendPlugin\Resolver\ProductImageResolver
    arguments:
      - '@liip_imagine.cache.manager'
      - '%nfq_sylius_omnisend_plugin.product_image.type%'
      - '%nfq_sylius_omnisend_plugin.product_image.filter%'
      - '%nfq_sylius_omnisend_plugin.product_image.default_image%'

  nfq_sylius_omnisend_plugin.builder.product_picker:
    class: NFQ\SyliusOmnisendPlugin\Builder\ProductPickerBuilder
    arguments:
      - '@nfq_sylius_omnisend_plugin.resolver.product_image'
      - '@sylius.product_variant_resolver.default'
      - '@sylius.calculator.product_variant_price'
      - '@sylius.context.channel.composite'
      - '@router'

  nfq_sylius_omnisend_plugin.twig.product_picker_extension:
    class: NFQ\SyliusOmnisendPlugin\Twig\ProductPickerExtension
    arguments:
      - '@nfq_sylius_omnisend_plugin.builder.product_picker'
      - '@serializer'
    tags:
      - { name: twig.extension }

  nfq_sylius_omnisend_plugin.product_picker_object_normalizer:
    public: true
    class: Symfony\Component\Serializer\Normalizer\ObjectNormalizer
    autoconfigure: false
    calls:
      - ['setSerializer', ['@serializer']]
    autowire: false
    arguments:
      - '@serializer.mapping.class_metadata_factory'
      - '@nfq_sylius_omnisend_plugin.serializer.name_converter.product_picker'
      - ~
      - '@property_info.reflection_extractor'

  nfq_sylius_omnisend_plugin.serializer.name_converter.product_picker:
    class: NFQ\SyliusOmnisendPlugin\Serializer\NameConverter\ProductPickerNameConverter

  nfq_sylius_omnisend_plugin.serializer.normalizer.product_picker:
    class: NFQ\SyliusOmnisendPlugin\Serializer\Normalizer\ProductPickerNormalizer
    arguments:
      - '@nfq_sylius_omnisend_plugin.product_picker_object_normalizer'
    tags:
      - { name: 'serializer.normalizer' }
