imports:
  - { resource: services/form_type_extensions.yaml }
  - { resource: services/block_events.yaml }
  - { resource: services/factories.yaml }
  - { resource: services/builders.yaml }
  - { resource: services/handlers.yaml }
  - { resource: services/serialiazers.yaml }
  - { resource: services/subscribers.yaml }
  - { resource: services/managers.yaml }
  - { resource: services/twig.yaml }

services:
  nfq_sylius_omnisend_plugin.resolver.product_image:
    class: NFQ\SyliusOmnisendPlugin\Resolver\ProductImageResolver
    arguments:
      - '@liip_imagine.cache.manager'
      - '%nfq_sylius_omnisend_plugin.product_image.type%'
      - '%nfq_sylius_omnisend_plugin.product_image.filter%'
      - '%nfq_sylius_omnisend_plugin.product_image.default_image%'

  nfq_sylius_omnisend_plugin.client.omnisend:
    class: NFQ\SyliusOmnisendPlugin\Client\OmnisendClient
    arguments:
      - '@httplug.client.omnisend'
      - '@serializer'
      - '@nfq_sylius_omnisend_plugin.client.message_factory'

  nfq_sylius_omnisend_plugin.client.message_factory:
    class: NFQ\SyliusOmnisendPlugin\Client\MessageFactory
    arguments:
      - '@sylius.context.channel.composite'
      - '@serializer'
